" interestind stess
noremap   [a<SPACE>   1k
noremap   [s<SPACE>   2k
noremap   [d<SPACE>   3k
noremap   [f<SPACE>   4k
noremap   [g<SPACE>   5k
noremap   [h<SPACE>   6k
noremap   [j<SPACE>   7k
noremap   [k<SPACE>   8k
noremap   [l<SPACE>   9k
noremap  [a;<SPACE>  10k
noremap  [aa<SPACE>  11k
noremap  [as<SPACE>  12k
noremap  [ad<SPACE>  13k
noremap  [af<SPACE>  14k
noremap  [ag<SPACE>  15k
noremap  [ah<SPACE>  16k
noremap  [aj<SPACE>  17k
noremap  [ak<SPACE>  18k
noremap  [al<SPACE>  19k
noremap  [s;<SPACE>  20k
noremap  [sa<SPACE>  21k
noremap  [ss<SPACE>  22k
noremap  [sd<SPACE>  23k
noremap  [sf<SPACE>  24k
noremap  [sg<SPACE>  25k
noremap  [sh<SPACE>  26k
noremap  [sj<SPACE>  27k
noremap  [sk<SPACE>  28k
noremap  [sl<SPACE>  29k
noremap  [d;<SPACE>  30k
noremap  [da<SPACE>  31k
noremap  [ds<SPACE>  32k
noremap  [dd<SPACE>  33k
noremap  [df<SPACE>  34k
noremap  [dg<SPACE>  35k
noremap  [dh<SPACE>  36k
noremap  [dj<SPACE>  37k
noremap  [dk<SPACE>  38k
noremap  [dl<SPACE>  39k
noremap  [f;<SPACE>  40k
noremap  [fa<SPACE>  41k
noremap  [fs<SPACE>  42k
noremap  [fd<SPACE>  43k
noremap  [ff<SPACE>  44k
noremap  [fg<SPACE>  45k
noremap  [fh<SPACE>  46k
noremap  [fj<SPACE>  47k
noremap  [fk<SPACE>  48k
noremap  [fl<SPACE>  49k
noremap  [g;<SPACE>  50k
noremap  [ga<SPACE>  51k
noremap  [gs<SPACE>  52k
noremap  [gd<SPACE>  53k
noremap  [gf<SPACE>  54k
noremap  [gg<SPACE>  55k
noremap  [gh<SPACE>  56k
noremap  [gj<SPACE>  57k
noremap  [gk<SPACE>  58k
noremap  [gl<SPACE>  59k
noremap  [h;<SPACE>  60k
noremap  [ha<SPACE>  61k
noremap  [hs<SPACE>  62k
noremap  [hd<SPACE>  63k
noremap  [hf<SPACE>  64k
noremap  [hg<SPACE>  65k
noremap  [hh<SPACE>  66k
noremap  [hj<SPACE>  67k
noremap  [hk<SPACE>  68k
noremap  [hl<SPACE>  69k
noremap  [j;<SPACE>  70k
noremap  [ja<SPACE>  71k
noremap  [js<SPACE>  72k
noremap  [jd<SPACE>  73k
noremap  [jf<SPACE>  74k
noremap  [jg<SPACE>  75k
noremap  [jh<SPACE>  76k
noremap  [jj<SPACE>  77k
noremap  [jk<SPACE>  78k
noremap  [jl<SPACE>  79k
noremap  [k;<SPACE>  80k
noremap  [ka<SPACE>  81k
noremap  [ks<SPACE>  82k
noremap  [kd<SPACE>  83k
noremap  [kf<SPACE>  84k
noremap  [kg<SPACE>  85k
noremap  [kh<SPACE>  86k
noremap  [kj<SPACE>  87k
noremap  [kk<SPACE>  88k
noremap  [kl<SPACE>  89k
noremap  [l;<SPACE>  90k
noremap  [la<SPACE>  91k
noremap  [ls<SPACE>  92k
noremap  [ld<SPACE>  93k
noremap  [lf<SPACE>  94k
noremap  [lg<SPACE>  95k
noremap  [lh<SPACE>  96k
noremap  [lj<SPACE>  97k
noremap  [lk<SPACE>  98k
noremap  [ll<SPACE>  99k
noremap [a;;<SPACE> 100k
noremap [a;a<SPACE> 101k
noremap [a;s<SPACE> 102k
noremap [a;d<SPACE> 103k
noremap [a;f<SPACE> 104k
noremap [a;g<SPACE> 105k
noremap [a;h<SPACE> 106k
noremap [a;j<SPACE> 107k
noremap [a;k<SPACE> 108k
noremap [a;l<SPACE> 109k
noremap [aa;<SPACE> 110k
noremap [aaa<SPACE> 111k
noremap [aas<SPACE> 112k
noremap [aad<SPACE> 113k
noremap [aaf<SPACE> 114k
noremap [aag<SPACE> 115k
noremap [aah<SPACE> 116k
noremap [aaj<SPACE> 117k
noremap [aak<SPACE> 118k
noremap [aal<SPACE> 119k
noremap [as;<SPACE> 120k
noremap [asa<SPACE> 121k
noremap [ass<SPACE> 122k
noremap [asd<SPACE> 123k
noremap [asf<SPACE> 124k
noremap [asg<SPACE> 125k
noremap [ash<SPACE> 126k
noremap [asj<SPACE> 127k
noremap [ask<SPACE> 128k
noremap [asl<SPACE> 129k
noremap [ad;<SPACE> 130k
noremap [ada<SPACE> 131k
noremap [ads<SPACE> 132k
noremap [add<SPACE> 133k
noremap [adf<SPACE> 134k
noremap [adg<SPACE> 135k
noremap [adh<SPACE> 136k
noremap [adj<SPACE> 137k
noremap [adk<SPACE> 138k
noremap [adl<SPACE> 139k
noremap [af;<SPACE> 140k
noremap [afa<SPACE> 141k
noremap [afs<SPACE> 142k
noremap [afd<SPACE> 143k
noremap [aff<SPACE> 144k
noremap [afg<SPACE> 145k
noremap [afh<SPACE> 146k
noremap [afj<SPACE> 147k
noremap [afk<SPACE> 148k
noremap [afl<SPACE> 149k
noremap [ag;<SPACE> 150k
noremap [aga<SPACE> 151k
noremap [ags<SPACE> 152k
noremap [agd<SPACE> 153k
noremap [agf<SPACE> 154k
noremap [agg<SPACE> 155k
noremap [agh<SPACE> 156k
noremap [agj<SPACE> 157k
noremap [agk<SPACE> 158k
noremap [agl<SPACE> 159k
noremap [ah;<SPACE> 160k
noremap [aha<SPACE> 161k
noremap [ahs<SPACE> 162k
noremap [ahd<SPACE> 163k
noremap [ahf<SPACE> 164k
noremap [ahg<SPACE> 165k
noremap [ahh<SPACE> 166k
noremap [ahj<SPACE> 167k
noremap [ahk<SPACE> 168k
noremap [ahl<SPACE> 169k
noremap [aj;<SPACE> 170k
noremap [aja<SPACE> 171k
noremap [ajs<SPACE> 172k
noremap [ajd<SPACE> 173k
noremap [ajf<SPACE> 174k
noremap [ajg<SPACE> 175k
noremap [ajh<SPACE> 176k
noremap [ajj<SPACE> 177k
noremap [ajk<SPACE> 178k
noremap [ajl<SPACE> 179k
noremap [ak;<SPACE> 180k
noremap [aka<SPACE> 181k
noremap [aks<SPACE> 182k
noremap [akd<SPACE> 183k
noremap [akf<SPACE> 184k
noremap [akg<SPACE> 185k
noremap [akh<SPACE> 186k
noremap [akj<SPACE> 187k
noremap [akk<SPACE> 188k
noremap [akl<SPACE> 189k
noremap [al;<SPACE> 190k
noremap [ala<SPACE> 191k
noremap [als<SPACE> 192k
noremap [ald<SPACE> 193k
noremap [alf<SPACE> 194k
noremap [alg<SPACE> 195k
noremap [alh<SPACE> 196k
noremap [alj<SPACE> 197k
noremap [alk<SPACE> 198k
noremap [all<SPACE> 199k
            
noremap   ]a<SPACE>   1j
noremap   ]s<SPACE>   2j
noremap   ]d<SPACE>   3j
noremap   ]f<SPACE>   4j
noremap   ]g<SPACE>   5j
noremap   ]h<SPACE>   6j
noremap   ]j<SPACE>   7j
noremap   ]k<SPACE>   8j
noremap   ]l<SPACE>   9j
noremap  ]a;<SPACE>  10j
noremap  ]aa<SPACE>  11j
noremap  ]as<SPACE>  12j
noremap  ]ad<SPACE>  13j
noremap  ]af<SPACE>  14j
noremap  ]ag<SPACE>  15j
noremap  ]ah<SPACE>  16j
noremap  ]aj<SPACE>  17j
noremap  ]ak<SPACE>  18j
noremap  ]al<SPACE>  19j
noremap  ]s;<SPACE>  20j
noremap  ]sa<SPACE>  21j
noremap  ]ss<SPACE>  22j
noremap  ]sd<SPACE>  23j
noremap  ]sf<SPACE>  24j
noremap  ]sg<SPACE>  25j
noremap  ]sh<SPACE>  26j
noremap  ]sj<SPACE>  27j
noremap  ]sk<SPACE>  28j
noremap  ]sl<SPACE>  29j
noremap  ]d;<SPACE>  30j
noremap  ]da<SPACE>  31j
noremap  ]ds<SPACE>  32j
noremap  ]dd<SPACE>  33j
noremap  ]df<SPACE>  34j
noremap  ]dg<SPACE>  35j
noremap  ]dh<SPACE>  36j
noremap  ]dj<SPACE>  37j
noremap  ]dk<SPACE>  38j
noremap  ]dl<SPACE>  39j
noremap  ]f;<SPACE>  40j
noremap  ]fa<SPACE>  41j
noremap  ]fs<SPACE>  42j
noremap  ]fd<SPACE>  43j
noremap  ]ff<SPACE>  44j
noremap  ]fg<SPACE>  45j
noremap  ]fh<SPACE>  46j
noremap  ]fj<SPACE>  47j
noremap  ]fk<SPACE>  48j
noremap  ]fl<SPACE>  49j
noremap  ]g;<SPACE>  50j
noremap  ]ga<SPACE>  51j
noremap  ]gs<SPACE>  52j
noremap  ]gd<SPACE>  53j
noremap  ]gf<SPACE>  54j
noremap  ]gg<SPACE>  55j
noremap  ]gh<SPACE>  56j
noremap  ]gj<SPACE>  57j
noremap  ]gk<SPACE>  58j
noremap  ]gl<SPACE>  59j
noremap  ]h;<SPACE>  60j
noremap  ]ha<SPACE>  61j
noremap  ]hs<SPACE>  62j
noremap  ]hd<SPACE>  63j
noremap  ]hf<SPACE>  64j
noremap  ]hg<SPACE>  65j
noremap  ]hh<SPACE>  66j
noremap  ]hj<SPACE>  67j
noremap  ]hk<SPACE>  68j
noremap  ]hl<SPACE>  69j
noremap  ]j;<SPACE>  70j
noremap  ]ja<SPACE>  71j
noremap  ]js<SPACE>  72j
noremap  ]jd<SPACE>  73j
noremap  ]jf<SPACE>  74j
noremap  ]jg<SPACE>  75j
noremap  ]jh<SPACE>  76j
noremap  ]jj<SPACE>  77j
noremap  ]jk<SPACE>  78j
noremap  ]jl<SPACE>  79j
noremap  ]k;<SPACE>  80j
noremap  ]ka<SPACE>  81j
noremap  ]ks<SPACE>  82j
noremap  ]kd<SPACE>  83j
noremap  ]kf<SPACE>  84j
noremap  ]kg<SPACE>  85j
noremap  ]kh<SPACE>  86j
noremap  ]kj<SPACE>  87j
noremap  ]kk<SPACE>  88j
noremap  ]kl<SPACE>  89j
noremap  ]l;<SPACE>  90j
noremap  ]la<SPACE>  91j
noremap  ]ls<SPACE>  92j
noremap  ]ld<SPACE>  93j
noremap  ]lf<SPACE>  94j
noremap  ]lg<SPACE>  95j
noremap  ]lh<SPACE>  96j
noremap  ]lj<SPACE>  97j
noremap  ]lk<SPACE>  98j
noremap  ]ll<SPACE>  99j
noremap ]a;;<SPACE> 100j
noremap ]a;a<SPACE> 101j
noremap ]a;s<SPACE> 102j
noremap ]a;d<SPACE> 103j
noremap ]a;f<SPACE> 104j
noremap ]a;g<SPACE> 105j
noremap ]a;h<SPACE> 106j
noremap ]a;j<SPACE> 107j
noremap ]a;k<SPACE> 108j
noremap ]a;l<SPACE> 109j
noremap ]aa;<SPACE> 110j
noremap ]aaa<SPACE> 111j
noremap ]aas<SPACE> 112j
noremap ]aad<SPACE> 113j
noremap ]aaf<SPACE> 114j
noremap ]aag<SPACE> 115j
noremap ]aah<SPACE> 116j
noremap ]aaj<SPACE> 117j
noremap ]aak<SPACE> 118j
noremap ]aal<SPACE> 119j
noremap ]as;<SPACE> 120j
noremap ]asa<SPACE> 121j
noremap ]ass<SPACE> 122j
noremap ]asd<SPACE> 123j
noremap ]asf<SPACE> 124j
noremap ]asg<SPACE> 125j
noremap ]ash<SPACE> 126j
noremap ]asj<SPACE> 127j
noremap ]ask<SPACE> 128j
noremap ]asl<SPACE> 129j
noremap ]ad;<SPACE> 130j
noremap ]ada<SPACE> 131j
noremap ]ads<SPACE> 132j
noremap ]add<SPACE> 133j
noremap ]adf<SPACE> 134j
noremap ]adg<SPACE> 135j
noremap ]adh<SPACE> 136j
noremap ]adj<SPACE> 137j
noremap ]adk<SPACE> 138j
noremap ]adl<SPACE> 139j
noremap ]af;<SPACE> 140j
noremap ]afa<SPACE> 141j
noremap ]afs<SPACE> 142j
noremap ]afd<SPACE> 143j
noremap ]aff<SPACE> 144j
noremap ]afg<SPACE> 145j
noremap ]afh<SPACE> 146j
noremap ]afj<SPACE> 147j
noremap ]afk<SPACE> 148j
noremap ]afl<SPACE> 149j
noremap ]ag;<SPACE> 150j
noremap ]aga<SPACE> 151j
noremap ]ags<SPACE> 152j
noremap ]agd<SPACE> 153j
noremap ]agf<SPACE> 154j
noremap ]agg<SPACE> 155j
noremap ]agh<SPACE> 156j
noremap ]agj<SPACE> 157j
noremap ]agk<SPACE> 158j
noremap ]agl<SPACE> 159j
noremap ]ah;<SPACE> 160j
noremap ]aha<SPACE> 161j
noremap ]ahs<SPACE> 162j
noremap ]ahd<SPACE> 163j
noremap ]ahf<SPACE> 164j
noremap ]ahg<SPACE> 165j
noremap ]ahh<SPACE> 166j
noremap ]ahj<SPACE> 167j
noremap ]ahk<SPACE> 168j
noremap ]ahl<SPACE> 169j
noremap ]aj;<SPACE> 170j
noremap ]aja<SPACE> 171j
noremap ]ajs<SPACE> 172j
noremap ]ajd<SPACE> 173j
noremap ]ajf<SPACE> 174j
noremap ]ajg<SPACE> 175j
noremap ]ajh<SPACE> 176j
noremap ]ajj<SPACE> 177j
noremap ]ajk<SPACE> 178j
noremap ]ajl<SPACE> 179j
noremap ]ak;<SPACE> 180j
noremap ]aka<SPACE> 181j
noremap ]aks<SPACE> 182j
noremap ]akd<SPACE> 183j
noremap ]akf<SPACE> 184j
noremap ]akg<SPACE> 185j
noremap ]akh<SPACE> 186j
noremap ]akj<SPACE> 187j
noremap ]akk<SPACE> 188j
noremap ]akl<SPACE> 189j
noremap ]al;<SPACE> 190j
noremap ]ala<SPACE> 191j
noremap ]als<SPACE> 192j
noremap ]ald<SPACE> 193j
noremap ]alf<SPACE> 194j
noremap ]alg<SPACE> 195j
noremap ]alh<SPACE> 196j
noremap ]alj<SPACE> 197j
noremap ]alk<SPACE> 198j
noremap ]all<SPACE> 199j
